"""从 native_app/_version.py 重写 version_info.py（Windows exe 版本资源）。

发版 workflow 每次构建前执行；本地改完 _version.py 后也跑一遍再提交，
保证 exe 属性里的版本号不再和代码脱节。
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TEMPLATE = """\
# UTF-8
#
# Generated by scripts/gen_version_info.py from native_app/_version.py.
# Do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'Hein'),
        StringStruct('FileDescription', 'HainTag - 海茵的标签工坊'),
        StringStruct('FileVersion', '{version_string}'),
        StringStruct('InternalName', 'HainTag'),
        StringStruct('OriginalFilename', 'HainTag.exe'),
        StringStruct('ProductName', 'HainTag'),
        StringStruct('ProductVersion', '{version_string}'),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def main() -> int:
    version_file = ROOT / "native_app" / "_version.py"
    match = re.search(r'__version__\s*=\s*"([^"]+)"', version_file.read_text(encoding="utf-8"))
    if not match:
        print(f"cannot find __version__ in {version_file}", file=sys.stderr)
        return 1
    version = match.group(1)
    parts = [int(p) for p in re.findall(r"\d+", version)[:3]]
    while len(parts) < 3:
        parts.append(0)
    parts.append(0)

    out = ROOT / "version_info.py"
    out.write_text(
        TEMPLATE.format(
            version_tuple=tuple(parts),
            version_string=".".join(str(p) for p in parts),
        ),
        encoding="utf-8",
    )
    print(f"version_info.py <- {version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
